### ISSUE TITLE
Use proper Authorization token

### ISSUE THREAD

**Issue by jrconlin** [web-push-libs/vapid#19]
Standard has changed to specify the token is `WebPush`

https://github.com/web-push-libs/web-push/issues/200

**Comment by jrconlin** [comment]
Blocking on autopush deploy of https://github.com/mozilla-services/autopush/issues/592

**Comment by robbiet480** [comment]
Google has changed to using `WebPush` now according to [their docs](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/sending-messages#authorization-header).

**Comment by jrconlin** [comment]
closed #21
