### ISSUE TITLE
Library Feedback

### ISSUE THREAD

**Issue by gauntface** [web-push-libs/vapid#32]
Feedback from: @sergioburdisso
Imagine you wake up in the morning and say to yourself "today I feel like adding web push notifications to my web app", then you google "adding web push notifications to my web app", start doing this great codelab (it's really good and helpful, seriously), once you have completed, at the bottom of the codelab a link to a list of webpush libraries is given, you're so exited because you're this close to add web push notifications to app, only the server part remains; click on pywebpush to find something like this:

WebPusher(subscription_info).send(data, headers, ttl, gcm_key)
headers is a dictionary of additional HTTP header values (e.g. VAPID self identification headers)
VAPID? headers? ttl? what?... and that's it, VAPID links to pyvapid, once again, no documentations or examples... you feel lost and probably decide to give up on adding Web Push Notifications to your app.

Instead, what I tried to accomplish with solidwebpush was: once you've finished, you continue reading the example here, and that's it, you'll end up integrating web push in your application, for instance, not being aware that you're using VAPID (among other things), note that not a single "technical word" is given in the API documentation or in the README file of solidwebpush.

As I said, I think [solidwebpush](https://github.com/sergioburdisso/solidwebpush) is not a replacement for pywebpush, since it only works implementing VAPID (not the GCM API), so it is sort of an "easy-to-use" library for those who want to implement VAPID-based push notifications (for instance, those who've learned the "client part" from this codelab, even if they're not aware of it).

> NOTE From Myself: Maybe it would be good to assess how this API compares to the node web-push library and see if there is any changes that can be made to the API

**Comment by jrconlin** [comment]
Yeah, not really going to argue a lot. I'm working on a patch to at least reduce to a single call. Most of the time, you're sending just one message. 

It doesn't quite address the confusion about all the moving bits, but at least it lumps them together.

Thanks for passing along the feedback.

**Comment by sergioburdisso** [comment]
hi guys! maybe for those cases it would be fair for solidwebpush to be in the list of web-push libraries, but since I don't want to bother or cause any trouble to @marco-c or anyone and, after all, the only thing that matters the most are those folks, I could fork pywebpush and  see how to integrate the work done in solidwebpush, trying not to modify anything of what it already has as much as a can; Also I could improve the README file, write the API doc and creating a couple of examples (even if it means for me to do this job twice...)

**Comment by jrconlin** [comment]
@sergioburdisso If you want to add solidwebpush (or fork pywebpush), I'd strongly urge you to follow some of the python standards for things like flake8, having unit & integration tests (with full coverage), etc. These make it easier for others to help out as well as show if things break in the future. It's also a better solution to not break existing installations (not everyone does version locking). Like I said, I'm trying to at least combine pywebpush and py_vapid into a "one call does it all" approach that may be closer to how most folks would use it. The code is done, but I'm working on coverage and integration tests now. 

As for the documents, those can be a fair bit easier, and I'm never one to turn down help there. 

Thanks!

**Comment by Baalaarka** [comment]
Unable to generate Application server key in terminal with vapid --applicationServerKey, any suggestions for work arounds or alternate methods are really appreciated, Thanks!

**Comment by jrconlin** [comment]
Baalaarka, that was a bug. See #46. Thanks!
