### ISSUE TITLE
Python implementation doesn't enforce "aud" in claims during signing

### ISSUE THREAD

**Issue by hronik1** [web-push-libs/vapid#43]
Taking a a look at the spec, it appears that both "sub" and "aud" are required fields in a claim, so it strikes me that it should be enforced the same way that "sub" is within `sign()` and `_base_sign()`.

I'm fine contributing a PR to address if the maintainers feel my concern is valid :)

**Comment by jrconlin** [comment]
closed by #42 

Will push a new version to pypi monday, so as not to ruin anyone's weekend.
