### ISSUE TITLE
Needs documentation for client-side applicationServerKey paramater

### ISSUE THREAD

**Issue by Flimm** [web-push-libs/vapid#45]
`pushManager.subscribe` takes the option `applicationServerKey` client-side. The Python documentation needs to document how to convert the generated public key into a form that can be used client-side like this.

```javascript
navigator.serviceWorker.register('serviceworker.js').then(
  function(serviceWorkerRegistration) {
    var options = {
      userVisibleOnly: true,
      applicationServerKey: applicationServerKey // <-- how do I convert the public key .pem to this?
    };
    serviceWorkerRegistration.pushManager.subscribe(options).then(
      // ...
  });
```

**Comment by jrconlin** [comment]
No idea why github doesn't want to link to you, but can you r? https://github.com/web-push-libs/vapid/pull/48 and see if that meets what you're thinking?

**Comment by Flimm** [comment]
See my comment in #48 .
