### ISSUE TITLE
AttributeError: type object 'Vapid01' has no attribute 'from_raw'

### ISSUE THREAD

**Issue by piano-man** [web-push-libs/vapid#53]
i get this error when the followng line executes in my flask server :
webpush(y,
                    data="hello",
                          vapid_private_key="BBdqtyrSzY8i77ejAHFmkQjmWtr3N4IxBsDl8fpjjHcPLkTAFG4ANjNUBXe6WU_5IcLKHdE-3uUAG7YvlpvPU7M",
                   vapid_claims={"sub": "mailto:icm2015003@iiita.ac.in"})

here,y is a dict type subscription object

**Comment by jrconlin** [comment]
I believe you need to update your py_vapid library.
