### ISSUE TITLE
Authentication header broken on recent Firefox versions

### ISSUE THREAD

**Issue by arlopurcell** [web-push-libs/vapid#68]
the vapid claims dict now requires the "exp" field. the webpush method should generate it if it's missing like it does for the "aud" field

**Comment by aripbak** [comment]
Dikirim dari Yahoo Mail di Android 
 
  Pada Sab, 5 Jan 2019 pada 4:49, Arlo Purcell<notifications@github.com> menulis:   
the vapid claims dict now requires the "exp" field. the webpush method should generate it if it's missing like it does for the "aud" field

**Comment by jrconlin** [comment]
This patch was landed: https://github.com/web-push-libs/pywebpush/commit/e30f7df85c875db7490311eeebf9166a3baaf041
