### ISSUE TITLE
support RFC 8292

### ISSUE THREAD

**Issue by samuelcolvin** [web-push-libs/vapid#74]
The python code seems to supports [draft-ietf-webpush-vapid-01](https://tools.ietf.org/html/draft-ietf-webpush-vapid-01) and [draft-ietf-webpush-vapid-02](https://tools.ietf.org/html/draft-ietf-webpush-vapid-02), with draft 1 still the default.

However according to those links there are draft 3 and 4 and then [RFC8292](https://tools.ietf.org/html/rfc8292) (if I'm interpreting ieft.org correctly).

Are there any significant changes between draft 2 and RFC? If so could this library be updated to support the RFC?

**Comment by jrconlin** [comment]
Thanks for the reminder.

For the most part, the VAPID content, process and methods remained the same across the various drafts. The most significant change came with [draft 03](https://tools.ietf.org/html/draft-ietf-webpush-vapid-03) when the Authorization scheme changed from "webpush" to "vapid". After that, the following revisions fix issues with the phrasing of the RFC proper (including cites, fixing typos, clarifying, etc.)

Still, I should make sure that this library uses the RFC specification by default. Thanks!

**Comment by samuelcolvin** [comment]
Thanks. 

Might also be worth noting in the python readme that this package is available on pypi, I assumed it wasn't and installed it manually before discovering it while reading the source for pywebpush.
