### ISSUE TITLE
Replacing nose

### ISSUE THREAD

**Issue by jayvdb** [web-push-libs/vapid#86]
nose is apparently going to break in Python 3.10 due to one of the pending deprecation.
It seems to have survived the cut of Python 3.9, but only just.  See https://github.com/nose-devs/nose/issues/1099

Is there a plan/preference to replace nose?

**Comment by jrconlin** [comment]
Thanks for that. I'll admit I've not been paying a ton of attention to nose.

I believe that pytest is a reasonable replacement for nose, with much the same approach, although I've not dived all that deep into seeing how to migrate the tests over to pytest.

**Comment by tirkarthi** [comment]
nose will stop working from Python 3.10. It seems the project uses `eq_` and `ok_` from nose. These can be converted into pytest style assertions with https://github.com/pytest-dev/nose2pytest/
