### ISSUE TITLE
Move jrconlin/vapid into this organization

### ISSUE THREAD

**Issue by Neustradamus** [web-push-libs/vapid#87]
@jrconlin: Can you move this original code into web-push-libs organization?

Steps to do:
- Create an temporary org, for example web-push-libs-temp
- Transfer web-push-libs/vapid into web-push-libs-temp/vapid
- Transfer your jrconlin/vapid into web-push-libs
- Transfer web-push-libs-temp/vapid in your personal account
- Remove the temporary org
- Merge the code in the main repository and all branches
- Add tags/releases in the new repo (based on the fork)
- Create a new temporary repo: jrconlin/vapid-issues
- Transfer all issues from jrconlin/vapid into jrconlin/vapid-issues
- Transfer jrconlin/vapid-issues into web-push-libs org
- Transfer all issues from web-push-libs/vapid-issues into web-push-libs/vapid
- Delete web-push-libs/vapid-issues
- Archive or delete jrconlin/vapid

It will be perfect now, no lost.

Linked to:
- https://github.com/jrconlin/vapid/issues/16

**Comment by jrconlin** [comment]
nope. I just archived the other repo instead.

**Comment by Neustradamus** [comment]
@jrconlin: One problem is the search, it is in the main source code, not in this fork.

Can you contact GitHub to disassociate the main repository?
- https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by Neustradamus** [comment]
@jrconlin: Have you done?

I need to create a new ticket?

**Comment by jrconlin** [comment]
Nope, and I don't really feel super compelled to do a lot of extra work for no real benefit. Can I ask why you're very interested in this?

**Comment by Neustradamus** [comment]
The goal is to have the main project here.

You must to send a little message to github to disassociate from your personal archive :)

It is really easy, and it will be perfect.

**Comment by jrconlin** [comment]
Ah, Ok. I see.

Yeah, nope.

**Comment by Neustradamus** [comment]
I do not understand your "Yeah, nope."

Do you do the request?

**Comment by jrconlin** [comment]
I do not intend to do the request.
I don't feel that it is necessary, easy, nor desirable.

**Comment by Neustradamus** [comment]
@jrconlin: It is possible to detach this fork from the original source?
- https://support.github.com/contact?tags=rr-forks

It will be better to search in code etc.
