### ISSUE TITLE
Host validation for 'sub' does not allow domains containing hyphen

### ISSUE THREAD

**Issue by ngdio** [web-push-libs/vapid#94]
The host validation introduced in https://github.com/web-push-libs/vapid/commit/871d67da40ca7bd8fff69b1555b517029f707ea4 does not allow domains that contain hyphens to pass through the check, although they should be perfectly valid domains.

Working: test@testingthis.org

Not working: test@testing-this.org

This is also causing the issue described in https://github.com/home-assistant/core/issues/48766.

**Comment by wshuman3** [comment]
I believe the PR that introduced this was #92 not #91

**Comment by wshuman3** [comment]
#96 should resolve this issue
